language: python

python:
    - "3.3"
    - "3.4"

services:
    - redis
    - mongodb
    - elasticsearch

install:
    - python setup.py install
    - pip install -r dev_requirements.txt

script:
    - nosetests
    - behave
    - flake8
